import jwt from 'jsonwebtoken';
import sanitizeHtml from 'sanitize-html';
import pool,{transaction} from '../config/database.js';
import { env } from '../config/env.js';
import { getRedis } from '../config/redis.js';
import { AppError } from '../errors/app.error.js';
import { clientIpHash } from '../utils/crypto.js';
import { getPagination,pageMeta } from '../utils/http.js';
import { writeAudit } from './audit.service.js';
import { cacheInvalidate,cacheRemember } from './cache.service.js';
import { enqueueRevalidation } from './revalidation.service.js';

const card=`a.id::text,a.title,a.slug,a.excerpt,COALESCE(tm.url,a.thumbnail_url) AS "thumbnailUrl",a.published_at AS "publishedAt",a.view_count AS "viewCount",a.comment_count AS "commentCount",jsonb_build_object('id',c.id::text,'name',c.name,'slug',c.slug) AS category,jsonb_build_object('id',au.id::text,'fullName',au.full_name,'slug',au.slug,'avatarUrl',au.avatar_url) AS author`;
const joins=`JOIN categories c ON c.id=a.category_id AND c.is_active AND c.deleted_at IS NULL LEFT JOIN authors au ON au.id=a.author_id LEFT JOIN media_assets tm ON tm.id=a.thumbnail_media_id AND tm.deleted_at IS NULL`;
const adminJoins=`JOIN categories c ON c.id=a.category_id LEFT JOIN authors au ON au.id=a.author_id LEFT JOIN media_assets tm ON tm.id=a.thumbnail_media_id`;
const published=`a.status='published' AND a.published_at<=now() AND a.deleted_at IS NULL`;
const sanitize=(html)=>sanitizeHtml(html,{allowedTags:sanitizeHtml.defaults.allowedTags.concat(['img','figure','figcaption','h1','h2','video','source']),allowedAttributes:{...sanitizeHtml.defaults.allowedAttributes,img:['src','alt','width','height','loading'],a:['href','name','target','rel'],video:['controls','poster'],source:['src','type']},allowedSchemes:['http','https','mailto'],transformTags:{a:sanitizeHtml.simpleTransform('a',{rel:'noopener noreferrer'})}});
const ensureArticle=async(client,id,user,lock=false)=>{const {rows}=await client.query(`SELECT a.*,au.user_id AS author_user_id FROM articles a LEFT JOIN authors au ON au.id=a.author_id WHERE a.id=$1 AND a.deleted_at IS NULL ${lock?'FOR UPDATE OF a':''}`,[id]);const article=rows[0];if(!article)throw new AppError(404,'Không tìm thấy bài viết','ARTICLE_NOT_FOUND');if(user.role==='author'&&String(article.created_by)!==user.id&&String(article.author_user_id)!==user.id)throw new AppError(403,'Bạn chỉ được quản lý bài viết của mình','FORBIDDEN');return article;};
const validatePublish=(article)=>{const missing=[];for(const [key,value] of Object.entries({title:article.title,slug:article.slug,content:article.content_html,category:article.category_id,author:article.author_id,thumbnail:article.thumbnail_media_id||article.thumbnail_url}))if(!value)missing.push(key);if(missing.length)throw new AppError(400,'Bài viết chưa đủ dữ liệu để xuất bản','ARTICLE_INCOMPLETE',{fields:{missing}});};
const relations=async(client,id,{tagIds,secondaryCategoryIds})=>{if(tagIds){await client.query('DELETE FROM article_tags WHERE article_id=$1',[id]);for(const value of [...new Set(tagIds)])await client.query('INSERT INTO article_tags(article_id,tag_id) VALUES($1,$2)',[id,value]);}if(secondaryCategoryIds){await client.query('DELETE FROM article_secondary_categories WHERE article_id=$1',[id]);for(const value of [...new Set(secondaryCategoryIds)])await client.query('INSERT INTO article_secondary_categories(article_id,category_id) VALUES($1,$2)',[id,value]);}};
const invalidateArticle=async(client,article,oldSlug)=>{await enqueueRevalidation({tags:['homepage','sitemap','rss',`article:${article.slug}`,`category:${article.category_slug||article.category_id}`,`author:${article.author_id}`],paths:[`/tin-tuc/${article.slug}`,...(oldSlug&&oldSlug!==article.slug?[`/tin-tuc/${oldSlug}`]:[])]},client);await cacheInvalidate('homepage*','article*','category*','tag*','author*','search*');};

export const homepage=()=>cacheRemember('homepage',60,async()=>{const [featured,sections,trending]=await Promise.all([
  pool.query(`SELECT ${card} FROM articles a ${joins} WHERE ${published} AND a.is_featured ORDER BY a.featured_order,a.published_at DESC LIMIT 3`),
  pool.query(`SELECT c.id::text,c.name,c.slug,COALESCE(jsonb_agg(x.item ORDER BY x.published_at DESC) FILTER(WHERE x.item IS NOT NULL),'[]') AS articles FROM categories c LEFT JOIN LATERAL(SELECT jsonb_build_object('id',a.id::text,'title',a.title,'slug',a.slug,'excerpt',a.excerpt,'thumbnailUrl',COALESCE(tm.url,a.thumbnail_url),'publishedAt',a.published_at,'author',jsonb_build_object('id',au.id::text,'fullName',au.full_name,'slug',au.slug)) item,a.published_at FROM articles a JOIN categories ac ON ac.id=a.category_id LEFT JOIN authors au ON au.id=a.author_id LEFT JOIN media_assets tm ON tm.id=a.thumbnail_media_id WHERE ${published} AND ac.path<@c.path ORDER BY a.published_at DESC LIMIT 5)x ON true WHERE c.parent_id IS NULL AND c.is_active AND c.show_in_menu AND c.deleted_at IS NULL GROUP BY c.id ORDER BY c.display_order`),
  getTrending('24h',10),
]);return {featured:featured.rows,sections:sections.rows,trending};});
export const getCategory=async(slug)=>{const {rows}=await pool.query(`SELECT id::text,name,slug,parent_id::text AS "parentId",path::text,meta_title AS "metaTitle",meta_desc AS "metaDesc" FROM categories WHERE slug=$1 AND is_active AND deleted_at IS NULL`,[slug]);if(!rows[0])throw new AppError(404,'Không tìm thấy chuyên mục','CATEGORY_NOT_FOUND');return rows[0];};
export const categoryArticles=async(slug,query)=>{const category=await getCategory(slug);const {page,limit,offset}=getPagination(query,50);const params=[category.id,limit,offset];const [{rows},{rows:count}]=await Promise.all([pool.query(`SELECT ${card} FROM articles a ${joins} JOIN categories root ON root.id=$1 WHERE ${published} AND c.path<@root.path ORDER BY a.published_at DESC LIMIT $2 OFFSET $3`,params),pool.query(`SELECT count(*) FROM articles a JOIN categories c ON c.id=a.category_id JOIN categories root ON root.id=$1 WHERE ${published} AND c.path<@root.path`,[category.id])]);return {category,items:rows,meta:pageMeta(count[0].count,page,limit)};};
export const articleDetail=async(slug)=>cacheRemember(`article:${slug}`,300,async()=>{let {rows}=await pool.query(`SELECT ${card},a.content_html AS "contentHtml",a.content_json AS "contentJson",a.meta_title AS "metaTitle",a.meta_desc AS "metaDesc",a.canonical_url AS "canonicalUrl",a.updated_at AS "updatedAt",COALESCE(jsonb_agg(DISTINCT jsonb_build_object('id',t.id::text,'name',t.name,'slug',t.slug)) FILTER(WHERE t.id IS NOT NULL),'[]') AS tags FROM articles a ${joins} LEFT JOIN article_tags at ON at.article_id=a.id LEFT JOIN tags t ON t.id=at.tag_id AND t.deleted_at IS NULL WHERE a.slug=$1 AND ${published} GROUP BY a.id,c.id,au.id,tm.url`,[slug]);if(!rows[0]){const old=await pool.query(`SELECT a.slug FROM article_slug_history h JOIN articles a ON a.id=h.article_id WHERE h.old_slug=$1 AND ${published}`,[slug]);if(old.rows[0])return {redirectSlug:old.rows[0].slug};throw new AppError(404,'Không tìm thấy bài viết','ARTICLE_NOT_FOUND');}const related=await pool.query(`SELECT ${card} FROM articles a ${joins} WHERE ${published} AND a.category_id=$1 AND a.id<>$2 ORDER BY a.published_at DESC LIMIT 5`,[rows[0].category.id,rows[0].id]);return {...rows[0],related:related.rows};});
export const getViews=async(slug)=>{const {rows}=await pool.query(`SELECT view_count FROM articles WHERE slug=$1 AND ${published}`,[slug]);if(!rows[0])throw new AppError(404,'Không tìm thấy bài viết','ARTICLE_NOT_FOUND');const pending=Number(await getRedis()?.hget(`${env.CACHE_NAMESPACE}:views:pending`,slug)||0);return Number(rows[0].view_count)+pending;};
export const recordView=async(slug,request)=>{const {rows}=await pool.query(`SELECT id FROM articles a WHERE slug=$1 AND ${published}`,[slug]);if(!rows[0])throw new AppError(404,'Không tìm thấy bài viết','ARTICLE_NOT_FOUND');const redis=getRedis();if(!redis){await pool.query('UPDATE articles SET view_count=view_count+1 WHERE id=$1',[rows[0].id]);await pool.query(`INSERT INTO article_views_daily(article_id,view_date,view_count) VALUES($1,current_date,1) ON CONFLICT(article_id,view_date) DO UPDATE SET view_count=article_views_daily.view_count+1`,[rows[0].id]);return getViews(slug);}const fingerprint=`${env.CACHE_NAMESPACE}:view-dedupe:${rows[0].id}:${clientIpHash(request)}:${request.get('user-agent')?.slice(0,80)||''}`;if(await redis.set(fingerprint,'1','EX',900,'NX'))await redis.hincrby(`${env.CACHE_NAMESPACE}:views:pending`,slug,1);return getViews(slug);};
export const getTrending=async(period='24h',limit=20)=>{const days=period==='7d'?7:1;const {rows}=await pool.query(`SELECT ${card},COALESCE(sum(v.view_count*exp(-0.18*(current_date-v.view_date))),0)::float AS "trendingScore" FROM articles a ${joins} LEFT JOIN article_views_daily v ON v.article_id=a.id AND v.view_date>=current_date-$1::int WHERE ${published} GROUP BY a.id,c.id,au.id,tm.url ORDER BY "trendingScore" DESC,a.published_at DESC LIMIT $2`,[days,limit]);return rows;};
export const tagArticles=async(slug,query)=>listingEntity('tags',slug,query);
export const authorArticles=async(slug,query)=>listingEntity('authors',slug,query);
const listingEntity=async(type,slug,query)=>{const table=type==='tags'?'tags':'authors';const name=type==='tags'?'name':'full_name';const {rows:entityRows}=await pool.query(`SELECT id::text,${name} AS name,slug${type==='authors'?',avatar_url AS "avatarUrl",bio,social_links AS "socialLinks"':''} FROM ${table} WHERE slug=$1 AND deleted_at IS NULL`,[slug]);if(!entityRows[0])throw new AppError(404,'Không tìm thấy dữ liệu','NOT_FOUND');const {page,limit,offset}=getPagination(query,50);const link=type==='tags'?'JOIN article_tags link ON link.article_id=a.id AND link.tag_id=$1':'WHERE a.author_id=$1';const where=type==='tags'?`WHERE ${published}`:`AND ${published}`;const [{rows},{rows:count}]=await Promise.all([pool.query(`SELECT ${card} FROM articles a ${joins} ${link} ${where} ORDER BY a.published_at DESC LIMIT $2 OFFSET $3`,[entityRows[0].id,limit,offset]),pool.query(`SELECT count(*) FROM articles a ${type==='tags'?'JOIN article_tags link ON link.article_id=a.id AND link.tag_id=$1 WHERE':'WHERE a.author_id=$1 AND'} ${published}`,[entityRows[0].id])]);return {entity:entityRows[0],items:rows,meta:pageMeta(count[0].count,page,limit)};};
export const search=async(query)=>{const q=String(query.q||'').trim();if(!q)return {items:[],meta:pageMeta(0,1,20)};const {page,limit,offset}=getPagination(query,50);const params=[q,limit,offset];const where=`${published} AND a.search_vector @@ plainto_tsquery('simple',unaccent($1))`;const [{rows},{rows:count}]=await Promise.all([pool.query(`SELECT ${card},ts_rank_cd(a.search_vector,plainto_tsquery('simple',unaccent($1))) AS rank FROM articles a ${joins} WHERE ${where} ORDER BY rank DESC,a.published_at DESC LIMIT $2 OFFSET $3`,params),pool.query(`SELECT count(*) FROM articles a WHERE ${where}`,[q])]);return {items:rows,meta:pageMeta(count[0].count,page,limit)};};
export const latestArticles=async(limit=50)=>(await pool.query(`SELECT ${card} FROM articles a ${joins} WHERE ${published} ORDER BY a.published_at DESC LIMIT $1`,[limit])).rows;
export const adminDetail=async(id,user)=>{await ensureArticle(pool,id,user);const {rows}=await pool.query(`SELECT a.*,a.id::text AS id,a.category_id::text AS "categoryId",a.author_id::text AS "authorId",a.thumbnail_media_id::text AS "thumbnailMediaId",a.og_media_id::text AS "ogMediaId",COALESCE(jsonb_agg(DISTINCT at.tag_id::text) FILTER(WHERE at.tag_id IS NOT NULL),'[]') AS "tagIds",COALESCE(jsonb_agg(DISTINCT sc.category_id::text) FILTER(WHERE sc.category_id IS NOT NULL),'[]') AS "secondaryCategoryIds" FROM articles a LEFT JOIN article_tags at ON at.article_id=a.id LEFT JOIN article_secondary_categories sc ON sc.article_id=a.id WHERE a.id=$1 GROUP BY a.id`,[id]);return rows[0];};

export const adminList=async(query,user)=>{const {page,limit,offset}=getPagination(query);const values=[`%${query.search||''}%`,query.status||null,query.categoryId||null,query.authorId||null,user.role==='author'?user.id:null,limit,offset];const where=`a.deleted_at IS NULL AND ($1='%%' OR a.title ILIKE $1 OR a.slug ILIKE $1) AND ($2::text IS NULL OR a.status=$2) AND ($3::bigint IS NULL OR a.category_id=$3) AND ($4::bigint IS NULL OR a.author_id=$4) AND ($5::bigint IS NULL OR a.created_by=$5 OR au.user_id=$5)`;const [{rows},{rows:count}]=await Promise.all([pool.query(`SELECT ${card},a.status,a.is_featured AS "isFeatured",a.scheduled_at AS "scheduledAt",a.version,a.updated_at AS "updatedAt" FROM articles a ${adminJoins} WHERE ${where} ORDER BY a.updated_at DESC LIMIT $6 OFFSET $7`,values),pool.query(`SELECT count(*) FROM articles a LEFT JOIN authors au ON au.id=a.author_id WHERE ${where}`,values.slice(0,5))]);return {items:rows,meta:pageMeta(count[0].count,page,limit)};};
export const createArticle=async(input,request)=>transaction(async(client)=>{const html=sanitize(input.contentHtml||'');const {rows}=await client.query(`INSERT INTO articles(title,slug,excerpt,content_json,content_html,thumbnail_media_id,category_id,author_id,is_featured,featured_order,meta_title,meta_desc,canonical_url,og_media_id,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$15) RETURNING *`,[input.title,input.slug,input.excerpt,input.contentJson,html,input.thumbnailMediaId,input.categoryId,input.authorId,input.isFeatured||false,input.featuredOrder||0,input.metaTitle,input.metaDesc,input.canonicalUrl,input.ogMediaId,request.user.id]);await relations(client,rows[0].id,input);await writeAudit(client,{request,actorId:request.user.id,action:'article.create',entityType:'article',entityId:rows[0].id});return rows[0];});
export const updateArticle=async(id,input,request)=>transaction(async(client)=>{const article=await ensureArticle(client,id,request.user,true);if(Number(input.version)!==article.version)throw new AppError(409,'Bài viết đã được người khác cập nhật','VERSION_CONFLICT',{currentVersion:article.version});await client.query(`INSERT INTO article_revisions(article_id,version,snapshot,created_by) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING`,[id,article.version,article,request.user.id]);const values={title:input.title??article.title,slug:input.slug??article.slug,excerpt:input.excerpt===undefined?article.excerpt:input.excerpt,content_json:input.contentJson===undefined?article.content_json:input.contentJson,content_html:input.contentHtml===undefined?article.content_html:sanitize(input.contentHtml),thumbnail_media_id:input.thumbnailMediaId===undefined?article.thumbnail_media_id:input.thumbnailMediaId,category_id:input.categoryId??article.category_id,author_id:input.authorId===undefined?article.author_id:input.authorId,is_featured:input.isFeatured??article.is_featured,featured_order:input.featuredOrder??article.featured_order,meta_title:input.metaTitle===undefined?article.meta_title:input.metaTitle,meta_desc:input.metaDesc===undefined?article.meta_desc:input.metaDesc,canonical_url:input.canonicalUrl===undefined?article.canonical_url:input.canonicalUrl,og_media_id:input.ogMediaId===undefined?article.og_media_id:input.ogMediaId};if(values.slug!==article.slug)await client.query('INSERT INTO article_slug_history(article_id,old_slug) VALUES($1,$2) ON CONFLICT DO NOTHING',[id,article.slug]);const {rows}=await client.query(`UPDATE articles SET title=$2,slug=$3,excerpt=$4,content_json=$5,content_html=$6,thumbnail_media_id=$7,category_id=$8,author_id=$9,is_featured=$10,featured_order=$11,meta_title=$12,meta_desc=$13,canonical_url=$14,og_media_id=$15,updated_by=$16 WHERE id=$1 RETURNING *`,[id,values.title,values.slug,values.excerpt,values.content_json,values.content_html,values.thumbnail_media_id,values.category_id,values.author_id,values.is_featured,values.featured_order,values.meta_title,values.meta_desc,values.canonical_url,values.og_media_id,request.user.id]);await relations(client,id,input);await writeAudit(client,{request,actorId:request.user.id,action:'article.update',entityType:'article',entityId:id});await invalidateArticle(client,{...rows[0]},article.slug);return rows[0];});
export const transition=async(id,action,input,request)=>transaction(async(client)=>{const article=await ensureArticle(client,id,request.user,true);const role=request.user.role;const allowed={submit:{from:['draft'],to:'in_review',roles:['author','editor','super_admin']},reject:{from:['in_review'],to:'draft',roles:['editor','super_admin']},publish:{from:['draft','in_review','scheduled'],to:'published',roles:['editor','super_admin']},schedule:{from:['draft','in_review'],to:'scheduled',roles:['editor','super_admin']},archive:{from:['published','scheduled'],to:'archived',roles:['editor','super_admin']},unpublish:{from:['published'],to:'draft',roles:['editor','super_admin']},cancel_schedule:{from:['scheduled'],to:'draft',roles:['editor','super_admin']}}[action];if(!allowed||!allowed.roles.includes(role)||!allowed.from.includes(article.status))throw new AppError(409,'Chuyển trạng thái không hợp lệ','INVALID_ARTICLE_TRANSITION');if(['publish','schedule'].includes(action))validatePublish(article);let publishedAt=article.published_at,scheduledAt=article.scheduled_at;if(action==='publish'){publishedAt=new Date();scheduledAt=null;}if(action==='schedule'){scheduledAt=new Date(input.scheduledAt);if(scheduledAt<=new Date())throw new AppError(400,'Thời gian lên lịch phải ở tương lai','INVALID_SCHEDULE');}if(['archive','unpublish','cancel_schedule'].includes(action))scheduledAt=null;const {rows}=await client.query('UPDATE articles SET status=$2,published_at=$3,scheduled_at=$4,updated_by=$5 WHERE id=$1 RETURNING *',[id,allowed.to,publishedAt,scheduledAt,request.user.id]);await writeAudit(client,{request,actorId:request.user.id,action:`article.${action}`,entityType:'article',entityId:id});await invalidateArticle(client,rows[0]);return rows[0];});
export const softDelete=async(id,request)=>transaction(async(client)=>{const article=await ensureArticle(client,id,request.user,true);await client.query('UPDATE articles SET deleted_at=now(),updated_by=$2 WHERE id=$1',[id,request.user.id]);await writeAudit(client,{request,actorId:request.user.id,action:'article.delete',entityType:'article',entityId:id});await invalidateArticle(client,article);});
export const restore=async(id,request)=>transaction(async(client)=>{const {rows}=await client.query(`UPDATE articles SET deleted_at=NULL,status='draft',updated_by=$2 WHERE id=$1 AND deleted_at IS NOT NULL RETURNING *`,[id,request.user.id]);if(!rows[0])throw new AppError(404,'Không tìm thấy bài đã xóa','ARTICLE_NOT_FOUND');await writeAudit(client,{request,actorId:request.user.id,action:'article.restore',entityType:'article',entityId:id});return rows[0];});
export const duplicate=async(id,request)=>transaction(async(client)=>{const article=await ensureArticle(client,id,request.user);const slug=`${article.slug}-copy-${Date.now()}`;const {rows}=await client.query(`INSERT INTO articles(title,slug,excerpt,content_json,content_html,thumbnail_media_id,category_id,author_id,meta_title,meta_desc,created_by,updated_by) SELECT title||' (Bản sao)',$2,excerpt,content_json,content_html,thumbnail_media_id,category_id,author_id,meta_title,meta_desc,$3,$3 FROM articles WHERE id=$1 RETURNING *`,[id,slug,request.user.id]);await client.query('INSERT INTO article_tags SELECT $2,tag_id FROM article_tags WHERE article_id=$1',[id,rows[0].id]);await client.query('INSERT INTO article_secondary_categories SELECT $2,category_id FROM article_secondary_categories WHERE article_id=$1',[id,rows[0].id]);await writeAudit(client,{request,actorId:request.user.id,action:'article.duplicate',entityType:'article',entityId:rows[0].id,metadata:{sourceId:id}});return rows[0];});
export const revisions=async(id,user)=>{await ensureArticle(pool,id,user);return (await pool.query(`SELECT id::text,version,created_by::text AS "createdBy",created_at AS "createdAt" FROM article_revisions WHERE article_id=$1 ORDER BY version DESC`,[id])).rows;};
export const restoreRevision=async(id,revisionId,request)=>transaction(async(client)=>{const article=await ensureArticle(client,id,request.user,true);const {rows}=await client.query('SELECT snapshot FROM article_revisions WHERE id=$1 AND article_id=$2',[revisionId,id]);if(!rows[0])throw new AppError(404,'Không tìm thấy revision','REVISION_NOT_FOUND');const s=rows[0].snapshot;await client.query(`INSERT INTO article_revisions(article_id,version,snapshot,created_by) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING`,[id,article.version,article,request.user.id]);const result=await client.query(`UPDATE articles SET title=$2,slug=$3,excerpt=$4,content_json=$5,content_html=$6,category_id=$7,author_id=$8,updated_by=$9 WHERE id=$1 RETURNING *`,[id,s.title,s.slug,s.excerpt,s.content_json,s.content_html,s.category_id,s.author_id,request.user.id]);await writeAudit(client,{request,actorId:request.user.id,action:'article.revision_restore',entityType:'article',entityId:id,metadata:{revisionId}});await invalidateArticle(client,result.rows[0],article.slug);return result.rows[0];});
export const previewToken=(id,user)=>jwt.sign({articleId:String(id),userId:user.id},env.PREVIEW_SECRET,{issuer:'news-portal-api',audience:'news-portal-preview',expiresIn:'15m'});
export const preview=async(token)=>{let payload;try{payload=jwt.verify(token,env.PREVIEW_SECRET,{issuer:'news-portal-api',audience:'news-portal-preview'});}catch{throw new AppError(401,'Preview token không hợp lệ','INVALID_PREVIEW_TOKEN');}const {rows}=await pool.query(`SELECT ${card},a.content_html AS "contentHtml",a.status,a.meta_title AS "metaTitle",a.meta_desc AS "metaDesc" FROM articles a ${joins} WHERE a.id=$1 AND a.deleted_at IS NULL`,[payload.articleId]);if(!rows[0])throw new AppError(404,'Không tìm thấy bài viết','ARTICLE_NOT_FOUND');return rows[0];};
