import sanitizeHtml from 'sanitize-html';
import pool,{transaction} from '../config/database.js';
import { env } from '../config/env.js';
import { AppError } from '../errors/app.error.js';
import { clientIpHash,sha256 } from '../utils/crypto.js';
import { getPagination,pageMeta } from '../utils/http.js';
import { writeAudit } from './audit.service.js';
import { cacheInvalidate } from './cache.service.js';

const enabled=()=>{if(!env.COMMENTS_ENABLED)throw new AppError(404,'Tính năng bình luận đang tắt','COMMENTS_DISABLED');};
export const publicList=async(slug,query)=>{enabled();const {page,limit,offset}=getPagination(query,50);const params=[slug,limit,offset];const [{rows},{rows:count}]=await Promise.all([pool.query(`SELECT cm.id::text,cm.parent_id::text AS "parentId",cm.name,cm.content,cm.created_at AS "createdAt" FROM comments cm JOIN articles a ON a.id=cm.article_id WHERE a.slug=$1 AND a.status='published' AND a.published_at<=now() AND a.deleted_at IS NULL AND cm.status='approved' ORDER BY cm.created_at LIMIT $2 OFFSET $3`,params),pool.query(`SELECT count(*) FROM comments cm JOIN articles a ON a.id=cm.article_id WHERE a.slug=$1 AND a.status='published' AND a.published_at<=now() AND a.deleted_at IS NULL AND cm.status='approved'`,[slug])]);return {items:rows,meta:pageMeta(count[0].count,page,limit)};};
export const submit=async(slug,input,request)=>{enabled();const content=sanitizeHtml(input.content,{allowedTags:[],allowedAttributes:{}}).trim();if(content.length<2)throw new AppError(400,'Nội dung bình luận không hợp lệ','INVALID_COMMENT');const {rows}=await pool.query(`INSERT INTO comments(article_id,parent_id,name,email_hash,content,ip_hash) SELECT a.id,$2,$3,$4,$5,$6 FROM articles a WHERE a.slug=$1 AND a.status='published' AND a.published_at<=now() AND a.deleted_at IS NULL AND ($2::bigint IS NULL OR EXISTS(SELECT 1 FROM comments parent WHERE parent.id=$2 AND parent.article_id=a.id AND parent.status='approved')) RETURNING id::text,status,created_at AS "createdAt"`,[slug,input.parentId||null,input.name,sha256(input.email.toLowerCase()),content,clientIpHash(request)]);if(!rows[0])throw new AppError(404,'Không tìm thấy bài viết hoặc bình luận cha hợp lệ','ARTICLE_OR_PARENT_NOT_FOUND');return rows[0];};
export const adminList=async(query)=>{const {page,limit,offset}=getPagination(query);const {rows}=await pool.query(`SELECT cm.id::text,cm.article_id::text AS "articleId",a.title AS "articleTitle",cm.parent_id::text AS "parentId",cm.name,cm.content,cm.status,cm.created_at AS "createdAt" FROM comments cm JOIN articles a ON a.id=cm.article_id WHERE ($1::text IS NULL OR cm.status=$1) ORDER BY cm.created_at DESC LIMIT $2 OFFSET $3`,[query.status||null,limit,offset]);const count=await pool.query('SELECT count(*) FROM comments WHERE ($1::text IS NULL OR status=$1)',[query.status||null]);return {items:rows,meta:pageMeta(count.rows[0].count,page,limit)};};
export const moderate=async(ids,status,request)=>transaction(async(client)=>{const before=await client.query(`SELECT article_id,count(*) FILTER(WHERE status='approved') approved FROM comments WHERE id=ANY($1::bigint[]) GROUP BY article_id`,[ids]);await client.query(`UPDATE comments SET status=$2,moderated_by=$3,moderated_at=now(),updated_at=now() WHERE id=ANY($1::bigint[])`,[ids,status,request.user.id]);const affected=[...new Set(before.rows.map(row=>row.article_id))];for(const articleId of affected){await client.query(`UPDATE articles SET comment_count=(SELECT count(*) FROM comments WHERE article_id=$1 AND status='approved') WHERE id=$1`,[articleId]);await writeAudit(client,{request,actorId:request.user.id,action:`comment.${status}`,entityType:'article',entityId:articleId,metadata:{commentIds:ids}});}await cacheInvalidate('article*','homepage*');return {updated:ids.length};});
