import { randomUUID } from 'node:crypto';
import { PutObjectCommand,DeleteObjectCommand,S3Client } from '@aws-sdk/client-s3';
import sharp from 'sharp';
import pool,{transaction} from '../config/database.js';
import { env } from '../config/env.js';
import { AppError } from '../errors/app.error.js';
import { getPagination,pageMeta } from '../utils/http.js';
import { writeAudit } from './audit.service.js';

const client=env.S3_ENDPOINT&&env.S3_ACCESS_KEY&&env.S3_SECRET_KEY?new S3Client({endpoint:env.S3_ENDPOINT,region:env.S3_REGION,forcePathStyle:env.S3_FORCE_PATH_STYLE,credentials:{accessKeyId:env.S3_ACCESS_KEY,secretAccessKey:env.S3_SECRET_KEY}}):null;
const publicUrl=(key)=>`${(env.S3_PUBLIC_URL||`${env.S3_ENDPOINT}/${env.S3_BUCKET}`).replace(/\/$/,'')}/${key}`;
const upload=async(key,body,mime)=>{if(!client)throw new AppError(503,'Object storage chưa được cấu hình','STORAGE_UNAVAILABLE');await client.send(new PutObjectCommand({Bucket:env.S3_BUCKET,Key:key,Body:body,ContentType:mime,CacheControl:'public,max-age=31536000,immutable'}));};
export const uploadImage=async(file,input,request)=>{if(!file)throw new AppError(400,'Thiếu file ảnh','FILE_REQUIRED');let metadata;try{metadata=await sharp(file.buffer,{failOn:'error'}).metadata();}catch{throw new AppError(400,'File không phải ảnh hợp lệ','INVALID_IMAGE');}if(!['jpeg','png','webp','avif'].includes(metadata.format))throw new AppError(415,'Định dạng ảnh không được hỗ trợ','UNSUPPORTED_MEDIA_TYPE');const base=`images/${new Date().toISOString().slice(0,10)}/${randomUUID()}`;const originalKey=`${base}.${metadata.format==='jpeg'?'jpg':metadata.format}`;await upload(originalKey,file.buffer,`image/${metadata.format}`);const webp=await sharp(file.buffer).rotate().resize({width:1600,height:1600,fit:'inside',withoutEnlargement:true}).webp({quality:82}).toBuffer();const thumb=await sharp(file.buffer).rotate().resize({width:640,height:360,fit:'cover'}).webp({quality:80}).toBuffer();await Promise.all([upload(`${base}-large.webp`,webp,'image/webp'),upload(`${base}-thumb.webp`,thumb,'image/webp')]);return transaction(async(db)=>{const {rows}=await db.query(`INSERT INTO media_assets(object_key,url,mime_type,size_bytes,width,height,alt_text,variants,owner_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id::text,object_key AS "objectKey",url,mime_type AS "mimeType",size_bytes AS "sizeBytes",width,height,alt_text AS "altText",variants,created_at AS "createdAt"`,[originalKey,publicUrl(originalKey),`image/${metadata.format}`,file.size,metadata.width,metadata.height,input.altText||null,{large:publicUrl(`${base}-large.webp`),thumbnail:publicUrl(`${base}-thumb.webp`)},request.user.id]);await writeAudit(db,{request,actorId:request.user.id,action:'media.upload',entityType:'media',entityId:rows[0].id});return rows[0];});};
export const list=async(query)=>{const {page,limit,offset}=getPagination(query);const search=`%${query.search||''}%`;const [{rows},{rows:count}]=await Promise.all([pool.query(`SELECT id::text,object_key AS "objectKey",url,mime_type AS "mimeType",size_bytes AS "sizeBytes",width,height,alt_text AS "altText",variants,owner_id::text AS "ownerId",created_at AS "createdAt" FROM media_assets WHERE deleted_at IS NULL AND (object_key ILIKE $1 OR COALESCE(alt_text,'') ILIKE $1) ORDER BY created_at DESC LIMIT $2 OFFSET $3`,[search,limit,offset]),pool.query(`SELECT count(*) FROM media_assets WHERE deleted_at IS NULL AND (object_key ILIKE $1 OR COALESCE(alt_text,'') ILIKE $1)`,[search])]);return {items:rows,meta:pageMeta(count[0].count,page,limit)};};
export const update=async(id,altText,request)=>transaction(async(db)=>{const {rows}=await db.query(`UPDATE media_assets SET alt_text=$2,updated_at=now() WHERE id=$1 AND deleted_at IS NULL RETURNING id::text,url,alt_text AS "altText"`,[id,altText]);if(!rows[0])throw new AppError(404,'Không tìm thấy media','MEDIA_NOT_FOUND');await writeAudit(db,{request,actorId:request.user.id,action:'media.update',entityType:'media',entityId:id});return rows[0];});
export const remove=async(id,request)=>transaction(async(db)=>{const reference=await db.query(`SELECT 1 FROM articles WHERE deleted_at IS NULL AND (thumbnail_media_id=$1 OR og_media_id=$1) LIMIT 1`,[id]);if(reference.rowCount)throw new AppError(409,'Media đang được bài viết sử dụng','MEDIA_IN_USE');const {rows}=await db.query('UPDATE media_assets SET deleted_at=now() WHERE id=$1 AND deleted_at IS NULL RETURNING object_key,variants',[id]);if(!rows[0])throw new AppError(404,'Không tìm thấy media','MEDIA_NOT_FOUND');if(client){const basePath=new URL(env.S3_PUBLIC_URL||`${env.S3_ENDPOINT}/${env.S3_BUCKET}`).pathname.replace(/\/$/,'');const variantKeys=Object.values(rows[0].variants||{}).map(url=>decodeURIComponent(new URL(url).pathname.slice(basePath.length+1)));const keys=[rows[0].object_key,...variantKeys];await Promise.allSettled(keys.map(Key=>client.send(new DeleteObjectCommand({Bucket:env.S3_BUCKET,Key}))));}await writeAudit(db,{request,actorId:request.user.id,action:'media.delete',entityType:'media',entityId:id});});
