import pool,{transaction} from '../config/database.js';
import { AppError } from '../errors/app.error.js';
import { writeAudit } from './audit.service.js';

const config={
  tags:{table:'tags',fields:`id::text,name,slug,created_at AS "createdAt",updated_at AS "updatedAt"`,input:['name','slug']},
  authors:{table:'authors',fields:`id::text,user_id::text AS "userId",full_name AS "fullName",slug,avatar_url AS "avatarUrl",bio,social_links AS "socialLinks",created_at AS "createdAt",updated_at AS "updatedAt"`,input:['user_id','full_name','slug','avatar_url','bio','social_links']},
};
const cfg=(type)=>{if(!config[type])throw new AppError(400,'Loại taxonomy không hợp lệ','INVALID_TAXONOMY');return config[type];};
export const list=async(type,search='')=>{const c=cfg(type);const {rows}=await pool.query(`SELECT ${c.fields} FROM ${c.table} WHERE deleted_at IS NULL AND ($1='' OR ${type==='tags'?'name':'full_name'} ILIKE '%'||$1||'%' OR slug ILIKE '%'||$1||'%') ORDER BY ${type==='tags'?'name':'full_name'} LIMIT 200`,[search]);return rows;};
export const create=async(type,input,request)=>transaction(async(client)=>{const c=cfg(type);const values=c.input.map(k=>input[k]??(k==='social_links'?{}:null));const placeholders=values.map((_,i)=>`$${i+1}`).join(',');const {rows}=await client.query(`INSERT INTO ${c.table}(${c.input.join(',')}) VALUES(${placeholders}) RETURNING ${c.fields}`,values);await writeAudit(client,{request,actorId:request.user.id,action:`${type}.create`,entityType:type,entityId:rows[0].id});return rows[0];});
export const update=async(type,id,input,request)=>transaction(async(client)=>{const c=cfg(type);const allowed=c.input.filter(k=>Object.hasOwn(input,k));if(!allowed.length)throw new AppError(400,'Không có dữ liệu cập nhật','VALIDATION_ERROR');const values=[id,...allowed.map(k=>input[k])];const sets=allowed.map((k,i)=>`${k}=$${i+2}`).join(',');const {rows}=await client.query(`UPDATE ${c.table} SET ${sets} WHERE id=$1 AND deleted_at IS NULL RETURNING ${c.fields}`,values);if(!rows[0])throw new AppError(404,'Không tìm thấy dữ liệu','NOT_FOUND');await writeAudit(client,{request,actorId:request.user.id,action:`${type}.update`,entityType:type,entityId:id});return rows[0];});
export const remove=async(type,id,request)=>transaction(async(client)=>{const c=cfg(type);const ref=type==='tags'?`SELECT 1 FROM article_tags WHERE tag_id=$1 LIMIT 1`:`SELECT 1 FROM articles WHERE author_id=$1 AND deleted_at IS NULL LIMIT 1`;if((await client.query(ref,[id])).rowCount)throw new AppError(409,'Không thể xóa vì đang được bài viết sử dụng','RESOURCE_IN_USE');const result=await client.query(`UPDATE ${c.table} SET deleted_at=now() WHERE id=$1 AND deleted_at IS NULL`,[id]);if(!result.rowCount)throw new AppError(404,'Không tìm thấy dữ liệu','NOT_FOUND');await writeAudit(client,{request,actorId:request.user.id,action:`${type}.delete`,entityType:type,entityId:id});});
export const mergeTag=async(sourceId,targetId,request)=>transaction(async(client)=>{if(String(sourceId)===String(targetId))throw new AppError(400,'Tag nguồn và đích phải khác nhau','INVALID_MERGE');await client.query(`INSERT INTO article_tags(article_id,tag_id) SELECT article_id,$2 FROM article_tags WHERE tag_id=$1 ON CONFLICT DO NOTHING`,[sourceId,targetId]);await client.query('DELETE FROM article_tags WHERE tag_id=$1',[sourceId]);const result=await client.query('UPDATE tags SET deleted_at=now() WHERE id=$1 AND deleted_at IS NULL',[sourceId]);if(!result.rowCount)throw new AppError(404,'Không tìm thấy tag nguồn','TAG_NOT_FOUND');await writeAudit(client,{request,actorId:request.user.id,action:'tags.merge',entityType:'tag',entityId:sourceId,metadata:{targetId}});});
