import pool,{transaction} from '../config/database.js';
import { AppError } from '../errors/app.error.js';
import { getPagination,pageMeta } from '../utils/http.js';
import { writeAudit } from './audit.service.js';
import { hashPassword } from './auth.service.js';

const fields=`id::text,email,full_name AS "fullName",avatar_url AS "avatarUrl",role,status,last_login_at AS "lastLoginAt",created_at AS "createdAt",updated_at AS "updatedAt"`;
export const listUsers=async(query)=>{const {page,limit,offset}=getPagination(query);const search=`%${query.search??''}%`;const values=[search,query.role||null,query.status||null,limit,offset];const where=`deleted_at IS NULL AND ($1='%%' OR email ILIKE $1 OR full_name ILIKE $1) AND ($2::text IS NULL OR role=$2) AND ($3::text IS NULL OR status=$3)`;const [{rows},{rows:count}]=await Promise.all([pool.query(`SELECT ${fields} FROM users WHERE ${where} ORDER BY created_at DESC LIMIT $4 OFFSET $5`,values),pool.query(`SELECT count(*) FROM users WHERE ${where}`,values.slice(0,3))]);return {items:rows,meta:pageMeta(count[0].count,page,limit)};};
export const createUser=async(input,request)=>transaction(async(client)=>{const passwordHash=await hashPassword(input.password);const {rows}=await client.query(`INSERT INTO users(email,password_hash,full_name,role,status) VALUES(lower($1),$2,$3,$4,$5) RETURNING ${fields}`,[input.email,passwordHash,input.fullName,input.role,input.status]);await writeAudit(client,{request,actorId:request.user.id,action:'user.create',entityType:'user',entityId:rows[0].id,metadata:{role:input.role}});return rows[0];});
export const updateUser=async(id,input,request)=>transaction(async(client)=>{const {rows:existing}=await client.query('SELECT * FROM users WHERE id=$1 AND deleted_at IS NULL FOR UPDATE',[id]);if(!existing[0])throw new AppError(404,'Không tìm thấy người dùng','USER_NOT_FOUND');if(String(id)===request.user.id&&((input.role&&input.role!==request.user.role)||input.status==='suspended'))throw new AppError(409,'Không thể tự hạ quyền hoặc tự khóa tài khoản','SELF_LOCKOUT');const values=[id,input.fullName??existing[0].full_name,input.avatarUrl===undefined?existing[0].avatar_url:input.avatarUrl,input.role??existing[0].role,input.status??existing[0].status];const {rows}=await client.query(`UPDATE users SET full_name=$2,avatar_url=$3,role=$4,status=$5 WHERE id=$1 RETURNING ${fields}`,values);if(input.status==='suspended')await client.query('UPDATE refresh_tokens SET revoked_at=COALESCE(revoked_at,now()) WHERE user_id=$1',[id]);await writeAudit(client,{request,actorId:request.user.id,action:'user.update',entityType:'user',entityId:id,metadata:{role:input.role,status:input.status}});return rows[0];});
export const deleteUser=async(id,request)=>transaction(async(client)=>{if(String(id)===request.user.id)throw new AppError(409,'Không thể tự xóa tài khoản','SELF_DELETE');const {rows:admins}=await client.query(`SELECT count(*) FROM users WHERE role='super_admin' AND status='active' AND deleted_at IS NULL`);const {rows:target}=await client.query('SELECT role FROM users WHERE id=$1 AND deleted_at IS NULL FOR UPDATE',[id]);if(!target[0])throw new AppError(404,'Không tìm thấy người dùng','USER_NOT_FOUND');if(target[0].role==='super_admin'&&Number(admins[0].count)<=1)throw new AppError(409,'Phải còn ít nhất một Super Admin hoạt động','LAST_SUPER_ADMIN');await client.query(`UPDATE users SET deleted_at=now(),status='suspended',email=email||'.deleted.'||id WHERE id=$1`,[id]);await client.query('UPDATE refresh_tokens SET revoked_at=COALESCE(revoked_at,now()) WHERE user_id=$1',[id]);await writeAudit(client,{request,actorId:request.user.id,action:'user.delete',entityType:'user',entityId:id});});
