import { Router } from 'express';
import { z } from 'zod';
import { allowRoles } from '../../middlewares/auth.middleware.js';
import { validate } from '../../middlewares/validate.middleware.js';
import * as articles from '../../services/article.service.js';
import { asyncHandler,success } from '../../utils/http.js';
const router=Router();const id=z.object({id:z.string().regex(/^\d+$/)});const slug=z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(300);const ids=z.array(z.string().regex(/^\d+$/)).max(100);
const body=z.object({title:z.string().min(3).max(300),slug,excerpt:z.string().max(1000).nullable().optional(),contentJson:z.unknown().nullable().optional(),contentHtml:z.string().max(2_000_000).optional(),thumbnailMediaId:z.string().regex(/^\d+$/).nullable().optional(),categoryId:z.string().regex(/^\d+$/),authorId:z.string().regex(/^\d+$/).nullable().optional(),tagIds:ids.optional(),secondaryCategoryIds:ids.optional(),isFeatured:z.boolean().optional(),featuredOrder:z.number().int().min(0).optional(),metaTitle:z.string().max(255).nullable().optional(),metaDesc:z.string().max(500).nullable().optional(),canonicalUrl:z.url().nullable().optional(),ogMediaId:z.string().regex(/^\d+$/).nullable().optional()});
router.get('/',asyncHandler(async(req,res)=>{const data=await articles.adminList(req.query,req.user);return success(res,data.items,{meta:data.meta});}));
router.get('/:id',validate({params:id}),asyncHandler(async(req,res)=>success(res,await articles.adminDetail(req.params.id,req.user))));
router.post('/',validate({body:body.strict()}),asyncHandler(async(req,res)=>success(res,await articles.createArticle(req.body,req),{status:201})));
router.patch('/:id',validate({params:id,body:body.partial().extend({version:z.number().int().positive()}).strict()}),asyncHandler(async(req,res)=>success(res,await articles.updateArticle(req.params.id,req.body,req))));
router.delete('/:id',validate({params:id}),asyncHandler(async(req,res)=>{await articles.softDelete(req.params.id,req);return res.status(204).send();}));
router.post('/:id/restore',allowRoles('editor','super_admin'),validate({params:id}),asyncHandler(async(req,res)=>success(res,await articles.restore(req.params.id,req))));
router.post('/:id/duplicate',validate({params:id}),asyncHandler(async(req,res)=>success(res,await articles.duplicate(req.params.id,req),{status:201})));
router.post('/:id/submit',validate({params:id}),asyncHandler(async(req,res)=>success(res,await articles.transition(req.params.id,'submit',{},req))));
router.post('/:id/reject',allowRoles('editor','super_admin'),validate({params:id,body:z.object({reason:z.string().min(3).max(1000)}).strict()}),asyncHandler(async(req,res)=>success(res,await articles.transition(req.params.id,'reject',req.body,req))));
router.post('/:id/publish',allowRoles('editor','super_admin'),validate({params:id}),asyncHandler(async(req,res)=>success(res,await articles.transition(req.params.id,'publish',{},req))));
router.post('/:id/schedule',allowRoles('editor','super_admin'),validate({params:id,body:z.object({scheduledAt:z.iso.datetime()}).strict()}),asyncHandler(async(req,res)=>success(res,await articles.transition(req.params.id,'schedule',req.body,req))));
for(const action of ['archive','unpublish','cancel_schedule'])router.post(`/:id/${action.replace('_','-')}`,allowRoles('editor','super_admin'),validate({params:id}),asyncHandler(async(req,res)=>success(res,await articles.transition(req.params.id,action,{},req))));
router.get('/:id/revisions',validate({params:id}),asyncHandler(async(req,res)=>success(res,await articles.revisions(req.params.id,req.user))));
router.post('/:id/revisions/:revisionId/restore',allowRoles('editor','super_admin'),validate({params:z.object({id:z.string().regex(/^\d+$/),revisionId:z.string().regex(/^\d+$/)})}),asyncHandler(async(req,res)=>success(res,await articles.restoreRevision(req.params.id,req.params.revisionId,req))));
router.post('/:id/preview-token',validate({params:id}),asyncHandler(async(req,res)=>success(res,{token:articles.previewToken(req.params.id,req.user),expiresInSeconds:900})));
export default router;
